// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwvnAyPRzQZKhprVkN8h3lfL2XXoCiuEI',
    appId: '1:1089675818188:web:5b1203c2d70ed8a19fbe69',
    messagingSenderId: '1089675818188',
    projectId: 'flutter-nobi',
    authDomain: 'flutter-nobi.firebaseapp.com',
    storageBucket: 'flutter-nobi.appspot.com',
    measurementId: 'G-XQSMNMM9X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjaXVKIolBl6dNNEbVfOIcngRxZ7zi1sY',
    appId: '1:1089675818188:android:65568ac49b3681699fbe69',
    messagingSenderId: '1089675818188',
    projectId: 'flutter-nobi',
    storageBucket: 'flutter-nobi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwlSX-Yp1lZudJlTLuiWBuQ26JXgPXuqw',
    appId: '1:1089675818188:ios:8f507bad086634cd9fbe69',
    messagingSenderId: '1089675818188',
    projectId: 'flutter-nobi',
    storageBucket: 'flutter-nobi.appspot.com',
    iosClientId: '1089675818188-n4eiebu4jsbghioglrm3i8hj79ln7lin.apps.googleusercontent.com',
    iosBundleId: 'com.example.desktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwlSX-Yp1lZudJlTLuiWBuQ26JXgPXuqw',
    appId: '1:1089675818188:ios:c3da12f14fbd47e19fbe69',
    messagingSenderId: '1089675818188',
    projectId: 'flutter-nobi',
    storageBucket: 'flutter-nobi.appspot.com',
    iosClientId: '1089675818188-3eg0p2dgjben6uui7ua9lo44v2oa2ss5.apps.googleusercontent.com',
    iosBundleId: 'com.example.desktop.RunnerTests',
  );
}
